------------------------------------------------------------------------

-- Garrysmod fastDL resources.lua file generated by ConfigCreator.com --

------------------------------------------------------------------------

-- Workshop Items (2652928689) --

resource.AddWorkshop( '283211438' ) -- Don Vito Corleone
resource.AddWorkshop( '576517817' ) -- ECPD Police Playermodels
resource.AddWorkshop( '2167043678' ) -- GTA V Families/Ballas NPC/Playermodel
resource.AddWorkshop( '2071385759' ) -- GTA V SAPR/Female LSPD NPC/Playermodel
resource.AddWorkshop( '2260358133' ) -- Kimonos [PM, Ragdoll]
resource.AddWorkshop( '2028581413' ) -- RP_SouthSide_Day
resource.AddWorkshop( '2648852476' ) -- S.W.A.T. [PMs]
resource.AddWorkshop( '2489073711' ) -- Sentry's 1940s Mafia Playermodel Pack
resource.AddWorkshop( '2131057232' ) -- [ArcCW] Arctic's Customizable Weapons (Base Only)
resource.AddWorkshop( '557962280' ) -- ULX
resource.AddWorkshop( '248302805' ) -- DarkRP
resource.AddWorkshop( '104482086' ) -- [Official] Precision Tool
resource.AddWorkshop( '113495466' ) -- Climb SWEP 2
resource.AddWorkshop( '137669824' ) -- Enhanced Damage Addon
resource.AddWorkshop( '149737736' ) -- AntiPlayerStuck
resource.AddWorkshop( '557962238' ) -- ULib
resource.AddWorkshop( '793317003' ) -- Widgets Disabler (more CPU power!)
resource.AddWorkshop( '1308262997' ) -- SNTE (Say No To Exploits - ONLY WORKSHOP COLLECTION)
resource.AddWorkshop( '104479831' ) -- Stacker STool
resource.AddWorkshop( '1169579845' ) -- Fps Booster
resource.AddWorkshop( '104603291' ) -- Extended Spawnmenu
resource.AddWorkshop( '2160669896' ) -- Dynamic Height + Crouch Fix
resource.AddWorkshop( '2155366756' ) -- VManip (Base)
resource.AddWorkshop( '2051674221' ) -- 3D Proximity Chat
resource.AddWorkshop( '1408509829' ) -- Tactical Leaning
resource.AddWorkshop( '673698301' ) -- Vape SWEP
resource.AddWorkshop( '803144421' ) -- Momo's prop protection
resource.AddWorkshop( '700647856' ) -- DarkRP : Traduction française HQ
resource.AddWorkshop( '406018213' ) -- [DarkRP] Keep pocket contents when disconnecting
resource.AddWorkshop( '412608410' ) -- ACU — Auto-Clear Utility
resource.AddWorkshop( '2317482090' ) -- [ArcCW] Black Ops Pack
resource.AddWorkshop( '467523611' ) -- Katana SWEP ( カタナSWEP -- スクリプト武器)
resource.AddWorkshop( '1162417168' ) -- Weapon Holsters with editor
resource.AddWorkshop( '2484983263' ) -- [ArcCW] Gunsmith Offensive Grenades
resource.AddWorkshop( '669642096' ) -- Drones Rewrite
resource.AddWorkshop( '2437373117' ) -- [simfphys] GTA IV Vehicles
resource.AddWorkshop( '2429099714' ) -- [Materials] GTAIV Shared Vehicle Textures
resource.AddWorkshop( '771487490' ) -- [simfphys] LUA Vehicles - Base
resource.AddWorkshop( '831680603' ) -- [simfphys] armed vehicles
resource.AddWorkshop( '2063690158' ) -- Proxy Color Tool
resource.AddWorkshop( '1514815567' ) -- Cigarette Factory [Workshop Content]
resource.AddWorkshop( '1421801961' ) -- Simple looting system
resource.AddWorkshop( '2147475268' ) -- [DarkRP] Advanced Gundealer NPC
resource.AddWorkshop( '675824914' ) -- Half-Life 2 Melee Pack
resource.AddWorkshop( '388725208' ) -- Graffiti Swep
resource.AddWorkshop( '683686832' ) -- [DarkRP] Ano Command - Anonymous Chat Command
resource.AddWorkshop( '2632827738' ) -- Disguise Kit for DarkRP
resource.AddWorkshop( '2208797760' ) -- [ArcCW] Charms: Props
resource.AddWorkshop( '163793759' ) -- Player Spawn Effect
resource.AddWorkshop( '1596554153' ) -- Breaching Charge
resource.AddWorkshop( '1917370391' ) -- Toggleable Fists (Unarmed/Hands)
resource.AddWorkshop( '1149344121' ) -- DarkRP Full Classic Advert
resource.AddWorkshop( '218869210' ) -- SGM Shared Textures
resource.AddWorkshop( '975506888' ) -- RHIB Boat
resource.AddWorkshop( '107590810' ) -- Drivable yacht
resource.AddWorkshop( '2244996078' ) -- [simfphys] M42 Truppenfahrrad
resource.AddWorkshop( '1415538438' ) -- [simfphys] Float Base
resource.AddWorkshop( '472640093' ) -- Grappling Knife
resource.AddWorkshop( '104536054' ) -- iMac
resource.AddWorkshop( '2681455276' ) -- GTA 5 - Worker [P.M/Ragdoll/NPC]
resource.AddWorkshop( '1428077445' ) -- GTA V Submersible
resource.AddWorkshop( '2691681813' ) -- Radar Speed Gun
resource.AddWorkshop( '1819166858' ) -- Ballistic Shields [Workshop Content]
resource.AddWorkshop( '2710278536' ) -- Ballistic Shield [SWEPs]
resource.AddWorkshop( '1247223957' ) -- NPC Guide
resource.AddWorkshop( '213181442' ) -- Mobile Computing Pack
resource.AddWorkshop( '1108535208' ) -- PC Monitors (pack)
resource.AddWorkshop( '2252176750' ) -- rHealth - rArmor | Simple Health and Armor NPC's
resource.AddWorkshop( '220336312' ) -- PermaProps
resource.AddWorkshop( '2155841271' ) -- [VManip] Contextual Animations
resource.AddWorkshop( '2690914262' ) -- Crunchy's Ultimate Item Pickups
resource.AddWorkshop( '107411755' ) -- FBI Playermodels
resource.AddWorkshop( '2406981049' ) -- [ArcCW] Gunsmith Offensive (Attachments Only)
resource.AddWorkshop( '2727897275' ) -- ArcCW - BellraD's Weaponry (V1.0)
resource.AddWorkshop( '1166337427' ) -- Dans Weapon Shelf Assets
resource.AddWorkshop( '2638230622' ) -- Darkrp meth lab - English version
resource.AddWorkshop( '1961791474' ) -- Hitman Fiber Wire SWEP
resource.AddWorkshop( '1734833080' ) -- The Cocaine Factory - Content
resource.AddWorkshop( '2031595057' ) -- KVSLib
resource.AddWorkshop( '2053017772' ) -- [CONTENT] Advanced Police Mod
resource.AddWorkshop( '677473509' ) -- [DarkRP] Pickpocket SWEP - Easy Config
resource.AddWorkshop( '108424005' ) -- Keypad Tool and Cracker with Wire Support
resource.AddWorkshop( '313279727' ) -- [C3] Police Badge SWEP
resource.AddWorkshop( '972895013' ) -- Police Radio Content
resource.AddWorkshop( '2607227837' ) -- Viktor Barinov (Chef)
resource.AddWorkshop( '948010619' ) -- Suited Citizens
resource.AddWorkshop( '2409867109' ) -- Suited Citizen NPCs
resource.AddWorkshop( '908491544' ) -- The Robber - GTA Online
resource.AddWorkshop( '753011279' ) -- OGBOSSHD's GTA Online character
resource.AddWorkshop( '769185719' ) -- Nigel - GTA 5
resource.AddWorkshop( '769146068' ) -- Josef - GTA 5
resource.AddWorkshop( '2446165379' ) -- HL2:Beta Wasteland Citizen Playermodel and NPC
resource.AddWorkshop( '2778699319' ) -- [VMAnip] Flashlight
resource.AddWorkshop( '2745446791' ) -- Viktor Barinov [NPC]
resource.AddWorkshop( '572775771' ) -- HL2 Beta Gas Mask Citizen Player & NPC
resource.AddWorkshop( '2689168958' ) -- MRS Content (Icons)
resource.AddWorkshop( '2486994157' ) -- MSD UI Content
